name: Desplegar Lambda en AWS - Test

on:
  push:
    branches:
      - test  # o la rama que uses

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repo de lambda actualizada
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # cambia si usas otra región

      - name: Instalar dependencias y crear ZIP
        run: |
          pip install -r requirements.txt -t .
          zip -r lambda.zip .

      - name: Desplegar a AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name nuv-test-github \
            --zip-file fileb://lambda.zip
