name: Desplegar Lambda en AWS - Test

on:
  push:
    branches:
      - test  # o la rama que uses

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repo de lambda actualizada
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} 
          aws-region: us-east-1  # cambia si usas otra región

      - name: Instalar dependencias y crear ZIP
        run: |
          sudo apt install zip
          python -m pip install --upgrade pip
          cd lambda1
          mkdir -p lambda_to_deploy
          pip install -r requirements.txt -t lambda_to_deploy
          cp lambda_function.py lambda_to_deploy
          cd lambda_to_deploy
          zip -r lambda_zip.zip *
      # Despliegue de una lambda ya existente
      - name: Desplegar a AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name nuv-test-github \
            --zip-file fileb://lambda1/lambda_to_deploy/lambda_zip.zip
